# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  DEPLOY_ID: ${{ github.run_id }}-${{ github.run_number }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Generate deployment package
      run: zip -r deploy.zip * .[^.]* -x "**node_modules**"
    
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACEESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy AWS EBS Application
      uses: betterchalk/ebs-deploy@v1
      with:
        ebs-app-name: ta123-api
        ebs-environment-name: Ta123api-env
        s3-bucket: elasticbeanstalk-us-east-1-371837554631
        s3-key: deploy.zip
        aws-region: us-east-1
        file-path: ./deploy.zip
        version-label: ${{ env.DEPLOY_ID }}
        process-timeout: 300
